Propagate changes of output value through Updateable::update() and Circuit::tick()
hellow554/logical-rs pull request #6
Opened 2019-08-19 11:56 UTC by dopsi

See #3

2019-08-19 12:54 UTC, hellow554 requested changes

2019-08-19 12:54 UTC, hellow554 commented on examples/fulladder.rs
> +        let mut cycle_count = 0_u32;
I (personally) don't like the `_u32` suffix. I wonder if it's really necessary here to give such a type hint or if Rust can deduce it by itself (probably to a `i32`). Can you remove it please?

2019-08-19 12:54 UTC, hellow554 commented on examples/fulladder.rs
> +        cycle_count += 1; // To get the correct number of cycles
Why not starting with `1` in the first place or using `cycle_count + 1` below in the `println!`?

2019-08-19 12:54 UTC, hellow554 commented on src/circuit.rs
> +    /// let mut clock_cycles = 0_u32;
Same here with the `_u32`

2019-08-19 12:54 UTC, hellow554 commented on src/circuit.rs
> +    /// let mut sig: logical::Signal<Ieee1164> = Signal::default();
`let mut sig: Signal<Ieee1164> = Signal::default();`

2019-08-19 13:01 UTC, hellow554 commented
https://github.com/hellow554/logical-rs/pull/6/files#diff-a6bffa6b46c2d189ffda6e7545e34e47R16

I'm not happy with this 🤔 You use it to determine, whether the value has been updated or not, correct? What if you instead use 

```
fn update(&mut self) -> bool {
    let new_value = $func(self.a.value());
    let old_value = self.z.replace(new_value);
    old_value != new_value
}
```

Because the values (in this case) are `Ieee1164` types, they are at least cloneable (copyable in this case)  this should work.

2019-08-19 14:07 UTC, dopsi commented on src/circuit.rs
> +    /// let mut sig: logical::Signal<Ieee1164> = Signal::default();
Indeed

2019-08-19 14:07 UTC, dopsi commented on examples/fulladder.rs
> +        cycle_count += 1; // To get the correct number of cycles
I'll fix that

2019-08-19 14:52 UTC, dopsi commented
You were correct that I used it to get the value before the change.

I now use a PortConnector, is that OK? It does not expose the internal API from inner port.

2019-08-19 15:36 UTC, hellow554 commented
> I now use a PortConnector, is that OK?

I see why you are doing it... I think I'm fine with accepting this currently, **but** I want a better solution for this.

2019-08-19 16:20 UTC, merged

2019-08-19 16:30 UTC, hellow554 commented
Closes #3

2019-08-19 19:43 UTC, dopsi commented
> I see why you are doing it... I think I'm fine with accepting this currently, **but** I want a better solution for this.

Would changing the signature of the closure from `FnOnce(&mut T)` to `FnOnce(&mut T) -> (T, T)` [here](https://github.com/hellow554/logical-rs/blob/master/src/port/pport.rs#L188)? In the return value, the first element in the tuple is the old value and the second the new value. The `with_value_mut` signature would be changed accordingly to

```rust
pub fn with_value_mut<F: FnOnce(&mut T) -> (T, T)>(&mut self, f: F) -> (T, T);
```

The other way would be to determine if the change happened inside the closure (having it return a `bool` and simply use it as the return value of the `update` function) but I feel this way is less generic and hand over the detection to the crate user instead of handling it internally.

2019-08-20 11:17 UTC, hellow554 commented
I thought about that at first glance as well, **but** `T` is not restricted in any way, therefore not even clone. This is done intentionally and I don't want to break that guarantee. 
Instead one should/could do things in the closure itself, e.g. cloning the inner value, because the closure knows what type is inside and whether it is clone or not.

2019-08-20 12:22 UTC, dopsi commented
I think we can then force the closure to notify the `with_value_mut` function where the value changed or not.