Remove use of PortConnector to access port value
hellow554/logical-rs pull request #7
Opened 2019-08-20 15:03 UTC by dopsi

Follow up to #6

2019-08-22 06:05 UTC, hellow554 requested changes

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/arithmic/add.rs
> +            old_value == v.clone()
We can save a clone by writing `old_value == *v` or `&old_value == &*v`

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/memory/rom.rs
>          println!("ROM Update");
Can you please remote this println, while you're at it 😅

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/memory/rom.rs
>          println!("{} {} {:?}", ncs, noe, data);
same here

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/memory/rom.rs
> +            old_value == f.clone()
clone isn't needed here as well

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/memory/rom.rs
> +                false
This makes me feel, that we should return a `Option<bool>` instead of a plain bool :/
But nevertheless, shouldn't this be true?

2019-08-22 06:05 UTC, hellow554 commented on src/models/rtlib/memory/rom.rs
> +                false
see above

2019-08-22 06:06 UTC, hellow554 commented
Sorry for the delay! And thank you very much again for your participation.
I have a few things annotated, please review them and rebase/squash the changes into the commit.

2019-08-23 15:47 UTC, dopsi commented on src/models/rtlib/memory/rom.rs
> +                false
It should indeed be true.

I had considered using an `Option<bool>` but since the value will either change or not change, I decided not to. In this particular case, the only problem is the fact we have no original value to compare the new value to, maybe `LogicVector::replace_with_int` should return `Result<bool, ()>` or `Result<u128, ()>`.

2019-08-24 17:50 UTC, merged